# Generated by Django 3.0.6 on 2020-05-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Está ativo?"),
        ),
    ]
